# Generated by Django 5.2.14 on 2026-09-05 07:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteSyncEndpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='A short label, e.g. "Oak" or "Building 34 fileserver".', max_length=100, unique=True)),
                ('host', models.CharField(help_text='e.g. dtn.oak.stanford.edu', max_length=255)),
                ('port', models.PositiveIntegerField(default=22)),
                ('username', models.CharField(help_text='Account name on the remote host.', max_length=150)),
                ('ssh_key_path', models.CharField(help_text="Path (on this NEMO server) to the private half of a keypair registered for public-key login on the remote host.", max_length=500)),
                ('base_path', models.CharField(help_text="Remote directory that every tool's own subdirectory lives under, e.g. /oak/stanford/orgs/nano", max_length=500)),
                ('extra_ssh_options', models.TextField(blank=True, help_text='Optional, one "Key Value" pair per line, appended as -o Key=Value to every connection')),
            ],
            options={
                'verbose_name': 'Remote sync endpoint',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SmartLabTool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Must exactly match a real NEMO Tool.name.', max_length=200, unique=True)),
                ('kind', models.CharField(choices=[('heater_log', 'Heater log (Veeco Fiji / Savannah ALD)'), ('mvd', 'MVD run folders (Cambridge Nanotech / Veeco MVD)'), ('waferlog', 'Wafer log (Plasma-Therm VersaLine)'), ('cobra_job', 'Cobra job database (Oxford PlasmaPro 100 Cobra / PTIQ)'), ('eventlog', 'Event log (KLA-DSE / Trikon-SPTS fxPLPXTMC)')], max_length=20)),
                ('local_root', models.CharField(help_text="Local path this tool's raw data is read from - a network share, or a directory kept mirrored by sync_remote_data from the Remote sync endpoint below.", max_length=500)),
                ('enabled', models.BooleanField(default=True, help_text='Uncheck to hide this tool from the Smart Lab dashboard.')),
                ('on_threshold_c', models.FloatField(blank=True, help_text='heater_log/mvd only - a heater channel above this many °C counts as "on". Blank uses the reader default (35.0).', null=True)),
                ('on_threshold_pct', models.FloatField(blank=True, help_text='mvd only - a heater channel with duty cycle above this percent counts as "on". Blank uses the reader default (0.5).', null=True)),
                ('stream_root', models.CharField(blank=True, help_text="cobra_job only, optional - local path to a synced copy of PTIQ/Databases/StreamedData, for the tool detail page's live telemetry section.", max_length=500)),
                ('stream_module', models.CharField(blank=True, default='PMC1', help_text='cobra_job only - the StreamedData module subfolder name.', max_length=100)),
                ('remote_subdir', models.CharField(blank=True, help_text="Directory name under the endpoint's base_path (e.g. the <toolname> in /oak/stanford/orgs/nano/<toolname>). Leave blank to use the tool name above as-is.", max_length=200)),
                ('last_synced', models.DateTimeField(blank=True, editable=False, null=True)),
                ('last_sync_ok', models.BooleanField(blank=True, editable=False, null=True)),
                ('last_sync_message', models.CharField(blank=True, editable=False, max_length=500)),
                ('real_id', models.PositiveIntegerField(blank=True, help_text="Optional - used only by seed_smart_lab_demo, to create/align a dev database's Tool at this exact primary key.", null=True)),
                ('real_category', models.CharField(blank=True, help_text="Optional - used only by seed_smart_lab_demo, as the demo Tool's category.", max_length=200)),
                ('sync_endpoint', models.ForeignKey(blank=True, help_text="Optional - if set, `sync_remote_data` mirrors this tool's data down from this endpoint into local_root.", null=True, on_delete=django.db.models.deletion.SET_NULL, to='smart_lab.remotesyncendpoint')),
            ],
            options={
                'verbose_name': 'Smart Lab tool',
                'ordering': ['name'],
            },
        ),
    ]
