# Generated by Django 5.2.17 on 2026-09-11 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NemoApiSource",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    models.CharField(help_text='A short label, e.g. "Stanford prod".', max_length=100, unique=True),
                ),
                ("api_root", models.URLField(help_text="Base REST API URL, e.g. https://nemo.stanford.edu/api")),
                (
                    "token",
                    models.CharField(
                        help_text="Value sent as 'Authorization: Token <this>' - read-only access is enough.",
                        max_length=200,
                    ),
                ),
                ("verify_ssl", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "NEMO API source (read-only)",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="smartlabtool",
            name="usage_reference_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional, read-only - if this tool's own local Reservation/UsageEvent history has nothing for a given run, NEMO_smart_lab.reservations.get_run_usage() will look the run up on this remote NEMO instance's API instead (GET only, never written back), using real_id above as that instance's Tool id. Leave blank to only ever use local data.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="smart_lab.nemoapisource",
            ),
        ),
        migrations.CreateModel(
            name="SmartLabToolChannel",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "channel_key",
                    models.CharField(
                        help_text='The raw channel name/number as shown today in the tool\'s channel table, e.g. "Heater 3" or "6".',
                        max_length=100,
                    ),
                ),
                (
                    "display_name",
                    models.CharField(help_text='Friendly name to show instead, e.g. "Source chuck".', max_length=200),
                ),
                (
                    "role",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("chuck", "Chuck"),
                            ("chamber", "Chamber wall"),
                            ("source_valve", "Source valve"),
                            ("precursor_line", "Precursor line"),
                            ("delivery_line", "Delivery line"),
                            ("exhaust", "Exhaust"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "tool",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="channel_labels",
                        to="smart_lab.smartlabtool",
                    ),
                ),
            ],
            options={
                "verbose_name": "Channel label",
                "ordering": ["tool", "channel_key"],
                "unique_together": {("tool", "channel_key")},
            },
        ),
    ]
