# Generated by Django 5.2.17 on 2026-09-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0002_nemoapisource_smartlabtool_usage_reference_source_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smartlabtoolchannel",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chuck", "Chuck"),
                    ("chamber", "Chamber wall"),
                    ("reactor", "Reactor"),
                    ("source_valve", "Source valve"),
                    ("precursor_line", "Precursor line"),
                    ("delivery_line", "Delivery line"),
                    ("exhaust", "Exhaust"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
