# Generated by Django 5.2.17 on 2026-09-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0003_alter_smartlabtoolchannel_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartlabtoolchannel",
            name="hidden",
            field=models.BooleanField(
                default=False,
                help_text="Hide this channel entirely from the tool's detail page and chart - for a schema slot that exists in the raw log format but isn't actually wired to anything on this particular tool (reads a constant 0 forever). display_name/role are ignored when set.",
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtoolchannel",
            name="display_name",
            field=models.CharField(
                blank=True,
                help_text='Friendly name to show instead, e.g. "Source chuck". Ignored if hidden.',
                max_length=200,
            ),
        ),
    ]
