# Generated by Django 5.2.17 on 2026-09-12 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0004_smartlabtoolchannel_hidden_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartlabtoolchannel",
            name="on_threshold_c",
            field=models.FloatField(
                blank=True,
                help_text="heater_log only - overrides the tool-wide on_threshold_c (SmartLabTool field) for just this one channel, e.g. a precursor jacket kept at a lower steady-state temperature than the reactor/chuck zones the tool-wide threshold is tuned for. Blank uses the tool-wide threshold.",
                null=True,
            ),
        ),
    ]
