# Generated by Django 5.2.17 on 2026-09-12 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0005_smartlabtoolchannel_on_threshold_c"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartlabtool",
            name="recipe_subdir",
            field=models.CharField(
                blank=True,
                help_text='Optional, read-only - directory name under remote_subdir holding this tool\'s recipe files (e.g. "Recipes" or "recipes" - varies per tool, check the exact case on the remote host). Leave blank to hide the Recipes tab for this tool entirely.',
                max_length=200,
            ),
        ),
    ]
