# Generated by Django 5.2.17 on 2026-09-12 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0006_smartlabtool_recipe_subdir"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartlabtool",
            name="recipe_channel_offset",
            field=models.IntegerField(
                default=0,
                help_text="heater_log only - a recipe file's \"heater\" step lines reference this tool's own physical channel numbering, which for some tools doesn't match the heater log file's own column numbering (channel_labels' \"Heater N\" keys) by a fixed amount - e.g. confirmed for fiji1/2/3: recipe channel 12 (\"Cone\") is the log's \"Heater 6\", a constant +6 offset (recipe_channel - offset = the log's number). Confirmed 0 (no translation needed) for savannah, where recipe channel numbers already match the log's own numbering directly. Not derivable automatically - verify against a real recipe file and this tool's existing channel_labels before setting. Irrelevant for mvd-kind tools (their recipe channel numbers already match channel_labels' bare-number keys as-is).",
            ),
        ),
    ]
