# Generated by Django 5.2.17 on 2026-09-12 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0007_smartlabtool_recipe_channel_offset"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="smartlabtool",
            options={
                "ordering": ["name"],
                "permissions": [
                    ("access_smart_lab", "Can access Smart Lab (beyond staff/superusers, who can always access it)")
                ],
                "verbose_name": "Smart Lab tool",
            },
        ),
    ]
