# Generated by Django 5.2.17 on 2026-09-12 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0008_alter_smartlabtool_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartlabtool",
            name="shutdown_recipe_keywords",
            field=models.CharField(
                blank=True,
                default="shutdown, shut down",
                help_text="Comma-separated, case-insensitive substrings - when the latest run's recipe name contains one of these and the tool isn't currently in use, the dashboard shows 'Shut down' instead of 'Ready'. Checked before standby/valve-clean. Blank disables this state for this tool.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="smartlabtool",
            name="standby_recipe_keywords",
            field=models.CharField(
                blank=True,
                default="standby",
                help_text="Comma-separated, case-insensitive substrings - when the latest run's recipe name contains one of these and the tool isn't currently in use, the dashboard shows 'Ready - standby' instead of a plain 'Ready'. Blank disables this state for this tool.",
                max_length=300,
            ),
        ),
        migrations.AddField(
            model_name="smartlabtool",
            name="valve_clean_recipe_keywords",
            field=models.CharField(
                blank=True,
                default="valve clean, clean valve",
                help_text="Comma-separated, case-insensitive substrings - when the latest run's recipe name contains one of these and the tool isn't currently in use, the dashboard shows 'Ready - valves clean' instead of a plain 'Ready'. Checked after shutdown/standby. Blank disables this state for this tool.",
                max_length=300,
            ),
        ),
    ]
