# Generated by Django 5.2.17 on 2026-09-12 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0009_smartlabtool_shutdown_recipe_keywords_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smartlabtoolchannel",
            name="role",
            field=models.CharField(
                blank=True,
                choices=[
                    ("chuck", "Chuck"),
                    ("chamber", "Chamber wall"),
                    ("reactor", "Reactor"),
                    ("source_valve", "Source valve"),
                    ("precursor_line", "Jacket"),
                    ("delivery_line", "Delivery line"),
                    ("exhaust", "Exhaust"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=20,
            ),
        ),
    ]
