# Generated by Django 5.2.17 on 2026-09-12 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0010_alter_smartlabtoolchannel_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="smartlabtool",
            name="valve_clean_recipe_keywords",
            field=models.CharField(
                blank=True,
                default="valve clean, clean valve, purge, clean, ozone clean, clear, clear0",
                help_text="Comma-separated, case-insensitive substrings - when the latest run's recipe name contains one of these and the tool isn't currently in use, the dashboard shows 'Ready - valves clean' instead of a plain 'Ready'. Checked after shutdown/standby. Blank disables this state for this tool.",
                max_length=300,
            ),
        ),
    ]
