# Generated by Django 5.2.17 on 2026-09-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0012_backfill_valve_clean_recipe_keywords"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartlabtool",
            name="pinned_recipe_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Recipe folder names (exact match, e.g. 'STANDARD' or 'Special Project') pinned to always sort first on this tool's Recipes page, ahead of even '(top level)'. Normally toggled from the small pin icon next to each folder heading there rather than edited here directly.",
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="valve_clean_recipe_keywords",
            field=models.CharField(
                blank=True,
                default="valve clean, clean valve, purge, clean, ozone clean, clear, clear0",
                help_text="Comma-separated, case-insensitive substrings - when the latest run's recipe name contains one of these and the tool isn't currently in use, the dashboard shows 'Ready - clean' instead of a plain 'Ready'. Checked after shutdown/standby. Blank disables this state for this tool.",
                max_length=300,
            ),
        ),
    ]
