# Generated by Django 5.2.17 on 2026-09-12 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0013_smartlabtool_pinned_recipe_categories_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartlabtool",
            name="base_pressure_recipe_name",
            field=models.CharField(
                blank=True,
                help_text="Exact recipe name (as embedded in the run filename/folder name, e.g. '20 - STANDBY 200C') to track for the chamber base-pressure history chart on the Run History page - the average of each matching run's last 10 seconds of pressure data, plotted over time. One *specific* recipe, not a keyword/substring: a tool often has several standby-ish variants (e.g. a plain standby vs. one that also runs a valve clean pass) with genuinely different baseline pressure, so mixing them would produce a misleading trend. Blank hides this chart for this tool.",
                max_length=200,
            ),
        ),
    ]
