# Generated by Django 5.2.17 on 2026-09-13 00:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0015_rename_base_pressure_recipe_name_to_plural"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartlabtool",
            name="config_subdir",
            field=models.CharField(
                blank=True,
                help_text='Optional, read-only - where this tool\'s configuration/settings files live (Setup.ini, config.ini, alarm/IO translation tables, etc.), for the read-only Config files tab. Either a real subfolder name under remote_subdir (e.g. "configuration" - confirmed for mvd/fiji5), or a literal "." if these files instead sit loose in the tool\'s own root folder, side by side with Logfile/Recipes (confirmed for fiji1/2/3\'s "Setup.ini.txt") - "." is browsed shallowly (just that one folder\'s own files), never a full recursive walk of the tool\'s entire remote tree. Leave blank to hide this tab for this tool entirely.',
                max_length=200,
            ),
        ),
    ]
