# Generated by Django 5.2.17 on 2026-09-13 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0016_smartlabtool_config_subdir"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="nemoapisource",
            options={"ordering": ["name"], "verbose_name": "Read-only NEMO remote API"},
        ),
        migrations.AlterField(
            model_name="remotesyncendpoint",
            name="extra_ssh_options",
            field=models.TextField(
                blank=True,
                help_text='Optional, one "Key Value" pair per line, appended as -o Key=Value to every connection - e.g. ControlPath ~/.ssh/%r@%h:%p plus ControlPersist yes to reuse an already-authenticated ControlMaster tunnel instead of a fresh SSH login per sync.',
            ),
        ),
        migrations.AlterField(
            model_name="remotesyncendpoint",
            name="ssh_key_path",
            field=models.CharField(
                help_text="Path (on this NEMO server) to the private half of a keypair registered for public-key login on the remote host. Password/2FA login isn't supported here - an unattended sync can't answer an interactive prompt.",
                max_length=500,
            ),
        ),
    ]
