# Generated by Django 5.2.17 on 2026-09-13 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0017_alter_nemoapisource_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nemoapisource",
            name="token",
            field=models.CharField(
                help_text="Sent as 'Authorization: Token <this>' - read-only access is enough.", max_length=200
            ),
        ),
        migrations.AlterField(
            model_name="remotesyncendpoint",
            name="base_path",
            field=models.CharField(
                help_text="Remote directory that each tool's own subdirectory lives under.", max_length=500
            ),
        ),
        migrations.AlterField(
            model_name="remotesyncendpoint",
            name="extra_ssh_options",
            field=models.TextField(blank=True, help_text='Optional extra SSH options, one "Key Value" pair per line.'),
        ),
        migrations.AlterField(
            model_name="remotesyncendpoint",
            name="ssh_key_path",
            field=models.CharField(
                help_text="Path to the private SSH key used to log in (password/2FA login isn't supported).",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="base_pressure_recipe_names",
            field=models.CharField(
                blank=True,
                help_text="Comma-separated, exact recipe names to track for the base pressure chart. Use 'Auto-detect standby recipes' below instead of typing these by hand. Blank hides the chart.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="config_subdir",
            field=models.CharField(
                blank=True,
                help_text="Folder holding this tool's configuration files. Use \".\" for the tool's own root folder. Blank hides this tab.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="local_root",
            field=models.CharField(help_text="Local path this tool's raw data is read from.", max_length=500),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="on_threshold_c",
            field=models.FloatField(
                blank=True,
                help_text='heater_log/mvd only - temperature (°C) counted as "on". Defaults to 35.0.',
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="on_threshold_pct",
            field=models.FloatField(
                blank=True, help_text='mvd only - duty cycle (%) counted as "on". Defaults to 0.5.', null=True
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="pinned_recipe_categories",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Recipe folders pinned to the top of the Recipes page. Usually toggled from that page directly.",
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="recipe_channel_offset",
            field=models.IntegerField(
                default=0,
                help_text="heater_log only - offset between a recipe's channel numbers and the heater log's own numbering.",
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="recipe_subdir",
            field=models.CharField(
                blank=True,
                help_text="Folder holding this tool's recipe files. Blank hides the Recipes tab.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="remote_subdir",
            field=models.CharField(
                blank=True,
                help_text="Directory name under the endpoint's base path. Blank uses the tool name above.",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="shutdown_recipe_keywords",
            field=models.CharField(
                blank=True,
                default="shutdown, shut down",
                help_text='Comma-separated keywords matched against the recipe name to show "Shut down".',
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="standby_recipe_keywords",
            field=models.CharField(
                blank=True,
                default="standby",
                help_text='Comma-separated keywords matched against the recipe name to show "Ready - standby".',
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="stream_module",
            field=models.CharField(
                blank=True,
                default="PMC1",
                help_text="cobra_job only - StreamedData module subfolder name.",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="stream_root",
            field=models.CharField(
                blank=True,
                help_text="cobra_job only - local path to synced PTIQ StreamedData, for live telemetry.",
                max_length=500,
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="sync_endpoint",
            field=models.ForeignKey(
                blank=True,
                help_text="If set, this tool's data is synced from this endpoint.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="smart_lab.remotesyncendpoint",
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="usage_reference_source",
            field=models.ForeignKey(
                blank=True,
                help_text="Optional fallback: look up usage on this remote NEMO API when there's no local match.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="smart_lab.nemoapisource",
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtool",
            name="valve_clean_recipe_keywords",
            field=models.CharField(
                blank=True,
                default="valve clean, clean valve, purge, clean, ozone clean, clear, clear0",
                help_text='Comma-separated keywords matched against the recipe name to show "Ready - clean".',
                max_length=300,
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtoolchannel",
            name="hidden",
            field=models.BooleanField(
                default=False, help_text="Hide this channel entirely from the tool's detail page and chart."
            ),
        ),
        migrations.AlterField(
            model_name="smartlabtoolchannel",
            name="on_threshold_c",
            field=models.FloatField(
                blank=True,
                help_text="heater_log only - overrides the tool-wide threshold for just this channel.",
                null=True,
            ),
        ),
    ]
