# Generated by Django 5.2.17 on 2026-09-13 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("smart_lab", "0018_alter_nemoapisource_token_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="smartlabtool",
            name="continuous_pressure_subdir",
            field=models.CharField(
                blank=True,
                help_text='Folder holding a continuous, always-on pressure log (rotating "<Name> - <timestamp>.txt" files, not per-run) - e.g. fiji5\'s "datalog/data/Pressure". Blank hides this chart.',
                max_length=200,
            ),
        ),
    ]
